version: '3.7'

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:8000"  # Changed from 80 to 8000
    ports:
      - "8000:80"  # Changed from 80 to 8000
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.toml:/etc/traefik/traefik.toml"
    networks:
      - web
    labels:
      - "traefik.http.routers.api.rule=Host(`proxy.chickenkiller.com`)"
      - "traefik.http.routers.api.service=api@internal"

  frontend:
    build:
      context: ./frontend
    labels:
      - "traefik.http.routers.frontend.rule=Host(`raven.chickenkiller.com`)"
    networks:
      - web

  backend:
    build:
      context: ./backend
    environment:
      - DATABASE_URL=postgresql://yourusername:yourpassword@db:5432/yourdbname
    labels:
      - "traefik.http.routers.backend.rule=Host(`raven.chickenkiller.com`) && PathPrefix(`/api`)"
    networks:
      - web

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: yourdbname
    networks:
      - web

  adminer:
    image: adminer
    ports:
      - "8081:8080"  # Changed from 8080 to 8081
    labels:
      - "traefik.http.routers.adminer.rule=Host(`db.chickenkiller.com`)"
    networks:
      - web

networks:
  web:
    external: true

